from showcov.core.config import LOG_FORMAT, get_schema
from showcov.core.core import (
    UncoveredSection,
    _get_xml_from_config,
    _get_xml_from_pyproject,
    build_sections,
    determine_xml_file,
    get_config_xml_file,
    group_consecutive_numbers,
    merge_blank_gap_groups,
)
from showcov.core.coverage import (
    BranchCondition,
    BranchGap,
    find_coverage_xml_paths,
    gather_uncovered_branches_from_xml,
    iter_lines,
    parse_condition_coverage,
    read_all_coverage_roots,
    read_coverage_xml_file,
)
from showcov.core.dataset import (
    CoverageDataset,
    FileCoverage,
    LineCoverage,
    Report,
    build_branches,
    build_dataset,
    build_diff,
    build_lines,
    build_summary,
)
from showcov.core.exceptions import (
    CoverageXMLError,
    CoverageXMLNotFoundError,
    InvalidCoverageXMLError,
    ShowcovError,
)
from showcov.core.files import detect_line_tag, normalize_path, read_file_lines
from showcov.core.path_filter import PathFilter
from showcov.core.thresholds import (
    Threshold,
    ThresholdFailure,
    ThresholdsResult,
    evaluate_thresholds,
    parse_threshold,
)
from showcov.core.types import (
    BranchMode,
    CoveragePercent,
    FilePath,
    Format,
    LineRange,
    SummarySort,
)

__all__ = [
    "LOG_FORMAT",
    "BranchCondition",
    "BranchGap",
    "BranchMode",
    "CoverageDataset",
    "CoveragePercent",
    "CoverageXMLError",
    "CoverageXMLNotFoundError",
    "FileCoverage",
    "FilePath",
    "Format",
    "InvalidCoverageXMLError",
    "LineCoverage",
    "LineRange",
    "PathFilter",
    "Report",
    "ShowcovError",
    "SummarySort",
    "Threshold",
    "ThresholdFailure",
    "ThresholdsResult",
    "UncoveredSection",
    "_get_xml_from_config",
    "_get_xml_from_pyproject",
    "build_branches",
    "build_dataset",
    "build_diff",
    "build_lines",
    "build_sections",
    "build_summary",
    "detect_line_tag",
    "determine_xml_file",
    "evaluate_thresholds",
    "find_coverage_xml_paths",
    "gather_uncovered_branches_from_xml",
    "get_config_xml_file",
    "get_schema",
    "group_consecutive_numbers",
    "iter_lines",
    "merge_blank_gap_groups",
    "normalize_path",
    "parse_condition_coverage",
    "parse_threshold",
    "read_all_coverage_roots",
    "read_coverage_xml_file",
    "read_file_lines",
]
